services:
  nextjs:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - "${DATABASE_PORT:-5432}:5432"  # host:container
    environment:
      POSTGRES_USER: lsd3_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: lsd3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - nextjs
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  certbot-run:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local