name: lsd3-website

services:
  nextjs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: ${TARGET:-prod}
    profiles: [ "dev", "prod" ]
    env_file:
      - ${ENV_FILE:-../.env}
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    profiles: [ "prod" ]
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app-network
    env_file:
      - ${ENV_FILE:-../.env}
    volumes:
      - pg_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    env_file:
      - ${ENV_FILE:-../.env}
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=disable",
      "up"
    ]
    networks:
      - app-network
    volumes:
      - ../migrations:/migrations

  nginx:
    image: nginx:alpine
    profiles: [ "prod" ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../certbot/conf:/etc/letsencrypt:ro
      - ../certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    depends_on:
      - nextjs
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M

  certbot:
    image: certbot/certbot
    profiles: [ "prod" ]
    volumes:
      - ../certbot/conf:/etc/letsencrypt:rw
      - ../certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  certbot-run:
    image: certbot/certbot
    profiles: [ "prod" ]
    volumes:
      - ../certbot/conf:/etc/letsencrypt:rw
      - ../certbot/www:/var/www/certbot:rw

networks:
  app-network:
    driver: bridge

volumes:
  pg_data: