name: lsd3-website-dev

services:
  nextjs:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
      target: dev
    env_file:
      - ${ENV_FILE:-../.env.dev}
    volumes:
      - ..:/app
      - ../tsconfig.json:/app/tsconfig.json
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 2G

  postgres:
    image: postgres:17
    profiles: [ "dev" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      retries: 5
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ${ENV_FILE:-../.env.dev}
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  migrate:
    env_file:
      - ${ENV_FILE:-../.env.dev}

volumes:
  pg_data_dev: