import { DateTime } from 'luxon';

import { EventCreateManyInput } from '@/lib/generated/prisma/models';
import { prisma } from '@/lib/prisma-client';

export function seedCalendarEvents() {
    const data: EventCreateManyInput[] = [
        {
            id: '0f18fc61-c828-478b-8ec2-5239bd1b1cd3',
            title: 'Board Meeting',
            description: 'Monthly board meeting',
            location: '1405 Gold Hill Rd, Newcastle, CA',
            start_at: DateTime.fromObject(
                { year: 2025, month: 2, day: 7, hour: 20, minute: 3 },
                { zone: 'America/Los_Angeles' },
            ).toJSDate(),
            end_at: DateTime.fromObject(
                { year: 2025, month: 2, day: 7, hour: 20, minute: 3 },
                { zone: 'America/Los_Angeles' },
            ).toJSDate(),
            timezone: 'America/Los_Angeles',
            all_day: false,
            event_type: 'meeting',
            is_members_only: false,
            is_published: true,
            content: `The Board Meeting is where the Chapter's officers gather to handle official business, review upcoming plans, and ensure everything runs smoothly behind the scenes. These meetings focus on decision-making, budgeting, event coordination, and any matters requiring leadership attention.
    
While typically limited to Board members and invited guests, all decisions made support the well-being of the Chapter, our charitable efforts, and the traditions of E Clampus Vitus. Topics commonly include:

- Financial Reports & Budgeting
- Event Planning & Logistics
- Charitable and Widder/Orphan Support Oversight
- Membership & Administrative Matters
- Long-Term Chapter Planning

Board Meetings keep the Chapter organized, accountable, and ready for the work ahead. Through careful planning and stewardship, the Board ensures that every event, donation, and gathering reflects the values and history we proudly uphold.`,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973Z',
            updated_at: '2025-12-03T18:17:49.973Z',
        },
        {
            id: 'ae8d0998-4348-4b0b-9ff3-71582d0860f1',
            title: 'General Meeting',
            description: 'Monthly regular business meeting for all members',
            location: '1405 Gold Hill Rd, Newcastle, CA',
            start_at: '2025-02-22T04:03:00.000Z',
            end_at: '2025-02-22T05:03:00.000Z',
            timezone: 'America/Los_Angeles',
            all_day: false,
            event_type: 'meeting',
            is_members_only: true,
            is_published: true,
            content: `Our General Meetings are held regularly to bring Redshirts together in the spirit of fellowship, history, and good works. These gatherings give us a chance to share upcoming events, discuss charitable efforts, plan Clampouts, and make sure every Brother stays connected with the Chapter's doings.
    
        All members in good standing are welcome. Whether you're a long-time Brother or newly inducted, the General Meeting is the place to stay involved, lend a hand, and help guide the Chapter's future. Meetings typically cover:
    
        - Upcoming Events & Work Parties
        - Charity and Widder/Orphan Support Updates
        - Chapter Business & Voting Matters
        - Historical Presentations or Local Lore
        - Social Time With Fellow Redshirts
    
        Come out, share your voice, and be part of the ongoing story of our Chapter. We meet to honor our history, support our community, and keep the spirit of E Clampus Vitus alive.`,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'bb63b259-8c5c-4c65-ac61-5626cdd38a50',
            title: 'Spring Doins',
            description: 'The Return to Foresthill!',
            location: 'Foresthill',
            start_at: '2025-04-25T07:03:00.000Z',
            end_at: '2025-04-27T07:03:00.000Z',
            meta: {
                links: [{ url: '/events/6030-spring-doins', text: 'Event Page' }],
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,

            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '147d7ba7-9a17-4981-8c94-47f439fd0d4a',
            title: 'Grand Council',
            description: '',
            location: '',
            start_at: '2025-05-16T00:00:00.000Z',
            end_at: '2025-05-18T23:59:59.999000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '55489448-83b4-4e92-a7fa-25d32da68fba',
            title: 'Pioneer Day Parade',
            description: '',
            location: 'Meadow Vista',
            start_at: '2025-06-01T00:00:00.000Z',
            end_at: '2025-06-01T00:00:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '46abb52f-9e97-4b8d-91d6-759dab9712d8',
            title: 'Wyoming 3-Way',
            description: '',
            location: 'Somewhere in Wyoming',
            start_at: '2025-06-27T00:00:00.000Z',
            end_at: '2025-06-29T23:59:59.999000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '1f79098a-5a33-43d9-b483-fced3d9a0ba2',
            title: '4th of July Parade',
            description: 'Annual Foresthill 4th of July parade',
            location: 'Foresthill',
            start_at: '2025-07-04T07:03:00.000Z',
            end_at: '2025-07-04T12:00:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '48324ee6-0398-46a8-91f1-b9bf4c9246f8',
            title: 'T.R.A.S.H.',
            description: '',
            location: 'Nobody knows',
            start_at: '2025-07-11T00:00:00.000Z',
            end_at: '2025-07-13T23:59:59.999000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'bd09f1b2-8fbf-4b9e-bd35-09febf522ec0',
            title: 'Fall Doins',
            description: '',
            location: '',
            start_at: '2025-09-19T00:00:00.000Z',
            end_at: '2025-09-21T12:00:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '3c5fc8f9-ff4a-4188-9df7-19b852edf7ee',
            title: 'Family Campout',
            description: '',
            location: '',
            start_at: null,
            end_at: null,
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '95f3516c-b139-40a8-bf8c-b1e258372a1a',
            title: "Widder's Ball",
            description: '',
            location: '',
            start_at: '2025-11-08T20:03:00.000Z',
            end_at: '2025-11-08T22:00:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '025fed3c-614f-48bb-a283-858bebab94bc',
            title: 'Receiving Home Toy Drive',
            description: 'Lets make it a Merry Christmas for the kids!',
            location: 'Walmart in Roseville',
            start_at: '2025-12-06T15:03:00.000Z',
            end_at: '2025-12-06T17:03:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '9bca4f62-9a80-42e5-96ac-39021f8d08db',
            title: 'Christmas Party',
            description: '',
            location: '',
            start_at: '2025-12-20T04:03:00.000Z',
            end_at: '2025-12-20T05:03:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'c54cd3f4-9d2e-494b-9539-1ed9b6823cf2',
            title: 'Election Night',
            description: '',
            location: '',
            start_at: '2026-01-17T04:03:00.000Z',
            end_at: '2026-01-17T05:03:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'a4534035-9286-4d22-974b-e86d17bd4cc2',
            title: 'Bean Feed',
            description: '',
            location: '',
            start_at: DateTime.fromObject(
                { year: 2026, month: 2, day: 7, hour: 7, minute: 33 },
                { zone: 'America/Los_Angeles' },
            ).toJSDate(),
            end_at: DateTime.fromObject(
                { year: 2026, month: 2, day: 7, hour: 15, minute: 33 },
                { zone: 'America/Los_Angeles' },
            ).toJSDate(),
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'a6795046-f3bd-43ab-abe3-a380a1e42c94',
            title: 'Spring Doins',
            description: '',
            location: '',
            start_at: '2026-04-17T07:03:00.000Z',
            end_at: '2026-04-19T15:03:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: '471ad577-0343-4a88-beb1-fc27246dc288',
            title: "LSD3 Gentleman's Initiation",
            description:
                "LSD3 is having a gentleman's initiation! There will be street tacos for donation and a 50/50 raffle! Widders are welcome! This is a great opportunity to bring in older or disabled PBC's",
            location: "Everybody's Inn 19420 Foresthill Rd, Foresthill, Ca.",
            start_at: '2025-08-23T10:03:00.000Z',
            end_at: '2025-08-23T14:03:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,

            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
        {
            id: 'e7e37769-7ecf-40fd-bea7-73756257e44a',
            title: 'LSD#3 Family Picnic and Camp Out',
            description:
                'ECV LSD3 Foresthill Family Camp Out! Bring the whole family out for a weekend of fun under the stars at the ECV LSD3 Foresthill Overnight Family Camp Out! Whether you’re staying the night or just dropping by for the day, there’s something for everyone!',
            location: 'Blackhawk Rd, Foresthill, CA.',
            start_at: '2025-08-16T11:00:00.000Z',
            end_at: '2025-08-17T11:00:00.000Z',
            all_day: false,
            timezone: 'America/Los_Angeles',
            event_type: 'other',
            is_members_only: false,
            is_published: true,
            meta: {
                start_date_tbd: false,
                end_date_tbd: false,
                start_time_tbd: false,
                end_time_tbd: false,
            },
            created_at: '2025-12-03T18:17:49.973277Z',
            updated_at: '2025-12-03T18:17:49.973277Z',
        },
    ];

    return prisma.event.createManyAndReturn({ data });
}
